name: Build NotiSms APK (no Android Studio)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    # Install Android commandline tools + set ANDROID_SDK_ROOT
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    # Accept licenses + install required SDK packages
    - name: Install Android packages
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew clean :app:assembleDebug --stacktrace

    - name: Show outputs tree (debugging)
      run: ls -R app/build/outputs || true

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: NotiSms-debug
        # grab any APK produced under outputs (module name is "app")
        path: |
          app/build/outputs/**/*.apk
        if-no-files-found: error
